# Generated by Django 6.0.7 on 2026-08-03 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('VENDOR', 'Vendor'), ('EXECUTIVE', 'Executive'), ('SUPER_ADMIN', 'Super Admin')], default='CUSTOMER', max_length=20),
        ),
    ]
