# Generated by Django 6.0.7 on 2026-07-31 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon_name', models.CharField(help_text='Flutter Icon name equivalent', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(max_length=255)),
                ('distance', models.CharField(blank=True, max_length=50)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('reviews_count', models.IntegerField(default=0)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('price_per_hour', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon_name', models.CharField(max_length=100)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='venues.venue')),
            ],
        ),
        migrations.CreateModel(
            name='VenueSport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venues.sport')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sports', to='venues.venue')),
            ],
        ),
    ]
