# Generated by Django 6.0.7 on 2026-08-04 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0003_venue_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='preregisteredvenue',
            name='real_venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preregistered_by', to='venues.venue'),
        ),
    ]
