# Generated by Django 6.0.7 on 2026-08-04 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
        ('users', '0002_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='current_score',
            field=models.JSONField(blank=True, default=dict, help_text='Current aggregated score for polling.'),
        ),
        migrations.AddField(
            model_name='sporttemplate',
            name='default_rules',
            field=models.JSONField(blank=True, default=dict, help_text='Default configuration for the sport.'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='organizer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organized_tournaments', to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='tournament_rules',
            field=models.JSONField(blank=True, default=dict, help_text='Overrides for default sport rules.'),
        ),
        migrations.CreateModel(
            name='SportEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('points_value', models.IntegerField(default=0)),
                ('requires_player', models.BooleanField(default=True)),
                ('sport_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tournaments.sporttemplate')),
            ],
        ),
        migrations.CreateModel(
            name='MatchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_time', models.DateTimeField(auto_now_add=True)),
                ('match_minute', models.IntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tournaments.match')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.userprofile')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_events', to='tournaments.team')),
                ('sport_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.sportevent')),
            ],
        ),
    ]
